#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#exec xset +fp /home/reueljohn/.fonts &
#exec xset fp rehash &
exec thunar --daemon &
exec nitrogen --restore &
exec compton -b &
#exec ~/.config/scripts/dwmstatus.sh &
exec ~/.config/scripts/polybarstart.sh &
exec mpd &
#exec awesome
#exec startkde
exec dwm
#exec i3
#exec openbox-session
